module.exports.viewAll = function(req, res, next) {
    const nfls =[ {
        id: 1,
        team: 'Bills',
        name: 'Josh Allen',
        hp: 85,
        type: '/images/Quarterback.png',
        image: '/images/JoshAllen.png',
        attackOne: 'Quarterback Rush',
        attackOneCost: 1,
        attackOneHP: 40,
        attackTwo: 'Hail Mary',
        attackTwoCost: 2,
        attackTwoHP: 60,
        weaknessType: '/images/DLinemen.png',
        resistanceType: '/images/Safety.png',
    },
    {
        id: 2,
        team: 'Chiefs',
        name: 'Patrick Mahomes',
        hp: 80,
        type: '/images/Quarterback.png',
        image: 'https://i2-prod.dailystar.co.uk/incoming/article21123568.ece/ALTERNATES/s1200c/1_GettyImages-1194337140.jpg',
        attackOne: 'Bullet Throw',
        attackOneCost: 1,
        attackOneHP: 30,
        attackTwo: 'Hail Mary',
        attackTwoCost: 2,
        attackTwoHP: 60,
        weaknessType: '/images/DLinemen.png',
        resistanceType: '/images/Safety.png',
    }];
    res.render('index', {nfls});
}